### ISSUE TITLE
Italian catalog update

### ISSUE THREAD

**Issue by samo79** [khval/BasiliskII-1.0#1]
Just updated the italian catalog translation for Basilisk II :-)
But i've uploaded it on a webserver as github seems not accepting lha attachments...

Please merge it in repo as you can :-)

http://s000.tinyupload.com/index.php?file_id=11185636066983895127

**Comment by khval** [comment]
Thanks Samo79, its somewhere in there now.

**Comment by samo79** [comment]
You welcome :-)
Aniway, i noted that currently in "italian" folder still the .cd file along with the .ct and the .catalog files.
However, perhaps you may remove the .cd file from there and mantain only the .ct and the .catalog files in italian directory
Same for the german translation

**Comment by khval** [comment]
@samo76

I was not sure if you had added anything to it.

**Comment by samo79** [comment]
In .cd file of course no, i did not added anything into it :-)
I waz used it just for compiling and nothing else but it's the same file that was already included in this repo .. you can remove it from the italian directory

**Comment by khval** [comment]
You need to do new translation, the .cd file was never up to date, I will make new commit soon with updated .cd file.

**Comment by samo79** [comment]
Ok, will update it asap :-)

**Comment by khval** [comment]
I try it now, it found that translations where never actually supported in the Reaction GUI, until now, got it fixed a few seconds ago.

**Comment by samo79** [comment]
Ok, link of the new updated catalog

http://s000.tinyupload.com/index.php?file_id=21795153428521446638

**Comment by samo79** [comment]
Found some typo that need corrections in basilisk.cd file

ID_PREFS_GFX_LOCK_GAD (//)
Screem lock

ID_PREFS_ID_3_UNIT_GAD (//)
Uinit 3

ID_PREFS_ID_5_UNIT_GAD (//)
unit 6

**Comment by samo79** [comment]
Ah.. forgot to mention, the same corrections should be applied also in basilisk.ct (the original file to fill)

**Comment by khval** [comment]
That file is automatically updated, when I compile Basilisk :-)
