### ISSUE TITLE
Italian translation updated

### ISSUE THREAD

**Issue by samo79** [khval/BasiliskII-1.0#7]
I have applied some corrections to the italian translation, here is the new files:

http://s000.tinyupload.com/index.php?file_id=09782812924860391391

Btw, not all parts of the interface seems translable yet... various parts still in english

**Comment by khval** [comment]
Link is not working.

**Comment by khval** [comment]
Maybe you make screenshot of the stuff that is not translated.

**Comment by samo79** [comment]
No, link is correct.. but the server is down
Let's try again later, if problem persist i will upload on another site

**Comment by samo79** [comment]
Strings missing are:

Disk
SCSI
IO
CPU
Graphics

name
size
RW

Partition

Window
Window composition
Full screen

Default
Black & White
4 colors (2bit)
16 colors (4bit)
256 colors  (8bit(
32 767 colors (15bit)

Internal conversion
System Write Pixel Array
Direct write (if possible)

Atleast that are the strings missing in the main GUI, but pretty possible there are even more such internal errors, program messages and so on ..

**Comment by samo79** [comment]
Link for the current translation updated

https://we.tl/t-Qcxxvp0kHm

**Comment by khval** [comment]
Yes, this where static lists, this is why they were tricky, because the string where set when program was started. I have changed some code, to fill in the arrays at runtime instead.

The only thing I have not fixed is the: “name,size,RW”

**Comment by samo79** [comment]
Ok very good, let me know when i can start updating my translation :-)

**Comment by khval** [comment]
You can do the translation now, all work done.

**Comment by samo79** [comment]
Ok, here the link of the new translation!

https://we.tl/t-kaiOvGxysf

P.S.
I've found eventually a new string tha you may be translable

"requester was cancelled"

It's printed in shell if you click cancel on a requester
However you may even suppress it as it's probably there only for debugging pourpose

**Comment by khval** [comment]
Yes, that text should be just removed.

**Comment by khval** [comment]
All issues here are now fixed.
